# This file creates an image that can be used to execute the unit tests.
#
# Usage:
#   # Build the image
#   docker build -f docker/Dockerfile-test -t fits-test .
#
#   # Run the tests
#   docker run --rm -v `pwd`:/fits:z -v ~/.m2:/root/.m2:z fits-test mvn clean test
#
#   # Interactive container access
#   docker run --rm -it -v `pwd`:/fits:z -v ~/.m2:/root/.m2:z fits-test

FROM docker.io/maven:3-eclipse-temurin-17

ARG FILE_VERSION=5.41
ARG FILE_SHA256=13e532c7b364f7d57e23dfeea3147103150cb90593a57af86c10e4f6e411603f

# Set timezone to eastern because some of the tests need this
RUN echo 'America/New_York' > /etc/timezone

RUN apt-get update && \
    apt-get install -yqq \
    # jpylyzer dependencies
    python3 \
    python-is-python3 \
    # exiftool dependencies https://github.com/exiftool/exiftool
    libarchive-zip-perl \
    libio-compress-perl \
    libcompress-raw-zlib-perl \
    libcompress-bzip2-perl \
    libcompress-raw-bzip2-perl \
    libio-digest-perl \
    libdigest-md5-file-perl \
    libdigest-perl-md5-perl \
    libdigest-sha-perl \
    libposix-strptime-perl \
    libunicode-linebreak-perl\
    # file dependencies
    make \
    gcc \
    # mediainfo dependencies
    libmms0 \
    libcurl3-gnutls \
    && rm -rf /var/lib/apt/lists/*

# Install file https://github.com/file/file
RUN cd /var/tmp && \
    curl -so file-${FILE_VERSION}.tar.gz https://astron.com/pub/file/file-${FILE_VERSION}.tar.gz && \
    echo "${FILE_SHA256}  file-${FILE_VERSION}.tar.gz" | sha256sum --check && \
    tar xzf file-${FILE_VERSION}.tar.gz && \
    cd file-${FILE_VERSION} && \
    ./configure && \
    make -j4 && \
    make install && \
    ldconfig && \
    cd .. && \
    rm -rf file-${FILE_VERSION}*

WORKDIR /fits

CMD ["bash"]
